name: "🐛 Bug report"
description: Report something broken
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: What happened?
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the system is affected?
      options:
        - Frontend (UI)
        - Backend (API)
        - Database
        - Auth / Permissions
        - Deploy / Docker
        - CI/CD
        - Docs
        - Other
    validations:
      required: true
