# Generated by Django 5.2.9 on 2025-12-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('access_mode', models.CharField(choices=[('PORT', 'PORT'), ('HOST', 'HOST')], default='PORT', max_length=10)),
                ('current_port', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('git_url', models.URLField()),
                ('default_branch', models.CharField(default='main', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('image_tag', models.CharField(blank=True, default='', max_length=200)),
                ('assigned_port', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('logs_path', models.CharField(blank=True, default='', max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='api.app')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.repository'),
        ),
    ]
