# Generated by Django 5.2.9 on 2025-12-21 19:41

import api.encrypted_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='container_port',
            field=models.IntegerField(default=8000, help_text='Port the container exposes'),
        ),
        migrations.AddField(
            model_name='app',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='Environment variables for container'),
        ),
        migrations.AddField(
            model_name='app',
            name='health_check_path',
            field=models.CharField(blank=True, default='', help_text='Optional health check path (e.g., /health)', max_length=200),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('update', 'Update'), ('rollback', 'Rollback')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_token',
            field=api.encrypted_fields.EncryptedTextField(blank=True, default='', help_text='GitHub PAT for private repos (encrypted at rest)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
